language: python
os: linux
dist: xenial
sudo: true

python:
#    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - sudo apt-get update -qq
    - sudo apt-get install gfortran
    - pip install --upgrade pip setuptools
    - pip install -r requirements_dev.txt

script:
    - pytest

after_success:
    - codecov
